; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 16MB Flash
board_build.partitions = default_16MB.csv

; 8MB PSRAM (Octal SPI)
board_build.arduino.memory_type = qio_opi
build_flags = -DBOARD_HAS_PSRAM

; the size of the flash memory that can be used for programming.
board_upload.flash_size = 16MB

; NeoPixel (WS2812) Library
lib_deps =
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
build_src_filter = +<*> -<test.cpp> ;compile everything except test.cpp

;environment to test oled screen and joystick
[env:esp32s3_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags = -DBOARD_HAS_PSRAM
board_upload.flash_size = 16MB
lib_deps =
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
build_src_filter = -<*> +<test.cpp>   ; only compile test.cpp